/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Metrics */
        get: operations["get_metrics_api_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Reviews */
        get: operations["list_reviews_api_reviews_get"];
        put?: never;
        /** Create Review */
        post: operations["create_review_api_reviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/by-outlook-item": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review By Outlook Item Query
         * @description Query-param variant for Outlook IDs containing slashes.
         */
        get: operations["get_review_by_outlook_item_query_api_reviews_by_outlook_item_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/by-outlook-item/{outlook_item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review By Outlook Item */
        get: operations["get_review_by_outlook_item_api_reviews_by_outlook_item__outlook_item_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/by-outlook-item/detach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detach Outlook Item Query
         * @description Query-param variant for Outlook IDs containing slashes.
         */
        post: operations["detach_outlook_item_query_api_reviews_by_outlook_item_detach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/by-outlook-item/{outlook_item_id}/detach": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Detach Outlook Item */
        post: operations["detach_outlook_item_api_reviews_by_outlook_item__outlook_item_id__detach_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/mark-opened": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark Review Opened
         * @description Record the first time the Review-UI was opened for ``review_id``.
         */
        post: operations["mark_review_opened_api_reviews__review_id__mark_opened_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Detail */
        get: operations["get_review_detail_api_reviews__review_id__get"];
        put?: never;
        post?: never;
        /** Delete Review */
        delete: operations["delete_review_api_reviews__review_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/mail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Mail */
        get: operations["get_review_mail_api_reviews__review_id__mail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/anfrage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Anfrage */
        put: operations["put_anfrage_api_reviews__review_id__anfrage_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/overrides": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Overrides */
        put: operations["put_overrides_api_reviews__review_id__overrides_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/requirements-ack": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Requirements Ack
         * @description Persist which extracted requirements have been acknowledged by the user.
         *
         *     Acknowledgments are stored by positional index. This is safe because the
         *     only path that changes a review's ``anforderungen`` is re-extraction, which
         *     runs exclusively via reset — and reset wipes every payload except the mail
         *     (``reset_review_state(keep={MAIL})``), clearing these acknowledgments too.
         *     So indices can never silently re-point at a different requirement. The
         *     range check below additionally rejects stale/out-of-range indices, and the
         *     quality gate fails safe (an unmatched index simply leaves a requirement
         *     unacknowledged, blocking approval rather than waving it through).
         */
        put: operations["put_requirements_ack_api_reviews__review_id__requirements_ack_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate Quotation
         * @description Recompute prices (and optionally rebuild the draft PDF).
         *
         *     During editing the UI passes ``build_pdf=false`` so each keystroke-blur
         *     only reprices (cheap); the draft PDF — only ever shown on the approval
         *     step — is rebuilt once when the user gets there.
         */
        post: operations["regenerate_quotation_api_reviews__review_id__regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/reply-body": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Reply Body
         * @description Generate a short, contextual cover-letter body for the Outlook reply.
         */
        get: operations["get_reply_body_api_reviews__review_id__reply_body_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize Quotation */
        post: operations["finalize_quotation_api_reviews__review_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Escalate Review
         * @description Flag a review for hand-off to Engineering/Plant (the as-is branch for
         *     inquiries Sales cannot answer automatically). Keeps the review and its
         *     audit trail; reset clears the flag like any other pipeline output.
         */
        post: operations["escalate_review_api_reviews__review_id__escalate_post"];
        /**
         * Clear Escalation
         * @description Withdraw an escalation (back to normal review).
         */
        delete: operations["clear_escalation_api_reviews__review_id__escalate_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Pipeline
         * @description Stop a running pipeline. Cooperative: drops queued steps and flags the
         *     run cancelled so the coordinator won't enqueue the next step. A step that
         *     is already executing finishes, but nothing further runs. No-op if the run
         *     isn't currently in progress.
         */
        post: operations["cancel_pipeline_api_reviews__review_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Review Events */
        get: operations["stream_review_events_api_reviews__review_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/attachment/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Attachment */
        get: operations["get_review_attachment_api_reviews__review_id__attachment__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/mail-attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Mail Attachments */
        get: operations["list_mail_attachments_api_reviews__review_id__mail_attachments_get"];
        put?: never;
        /** Upload Mail Attachment */
        post: operations["upload_mail_attachment_api_reviews__review_id__mail_attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/mail-attachments/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Mail Attachment */
        get: operations["get_mail_attachment_api_reviews__review_id__mail_attachments__filename__get"];
        put?: never;
        post?: never;
        /** Delete Mail Attachment */
        delete: operations["delete_mail_attachment_api_reviews__review_id__mail_attachments__filename__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/attachment/{filename}/pdf/highlight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Pdf Source Highlight */
        post: operations["get_pdf_source_highlight_api_reviews__review_id__attachment__filename__pdf_highlight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/original": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Original */
        get: operations["get_review_original_api_reviews__review_id__original_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/original/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Original Table */
        get: operations["preview_original_table_api_reviews__review_id__original_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Review */
        post: operations["upload_review_api_reviews_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stammdaten/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Stammdaten */
        get: operations["search_stammdaten_api_stammdaten_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/match-override": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Override Match */
        post: operations["override_match_api_reviews__review_id__match_override_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/matches/{pos_nr}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Manual Match */
        put: operations["set_manual_match_api_reviews__review_id__matches__pos_nr__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/custom-article": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Custom Article Match */
        post: operations["create_custom_article_match_api_reviews__review_id__custom_article_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Debug Info */
        get: operations["get_debug_info_api_debug_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/debug/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probe Llm Provider
         * @description Run an explicit, minimal provider call for the debug page.
         *
         *     The regular ``/debug`` endpoint only validates configuration. This
         *     endpoint intentionally performs a real LLM request, so the UI calls it
         *     only after a user action.
         */
        post: operations["probe_llm_provider_api_debug_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /** Put Settings */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Status */
        get: operations["get_review_status_api_reviews__review_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/approval": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval */
        get: operations["get_approval_api_reviews__review_id__approval_get"];
        put?: never;
        /** Post Approval */
        post: operations["post_approval_api_reviews__review_id__approval_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reset Review
         * @description Reset a review and re-run the pipeline against the saved mail.
         */
        post: operations["reset_review_api_reviews__review_id__reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review Pdf
         * @description Return the most appropriate PDF — final if approved, else draft.
         */
        get: operations["get_review_pdf_api_reviews__review_id__pdf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/pdf/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review Draft Pdf
         * @description Always return the draft PDF (with the red AI warning banner).
         */
        get: operations["get_review_draft_pdf_api_reviews__review_id__pdf_draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reviews/{review_id}/pdf/final": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review Final Pdf
         * @description Return the final PDF — only available after the user approves.
         */
        get: operations["get_review_final_pdf_api_reviews__review_id__pdf_final_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Anforderung
         * @description RFQ-level or position-level requirement that goes beyond standard fields.
         *
         *     Examples: "Bitte Zeichnung beilegen", "Material-Zertifikat 3.1 erforderlich",
         *     "Lieferung in Holzkiste", "Angebot bis Freitag erbeten".
         */
        Anforderung: {
            /** Text */
            text: string;
            /**
             * Kategorie
             * @enum {string}
             */
            kategorie: "zeichnung" | "zertifikat" | "verpackung" | "logistik" | "termin" | "sonstige";
            /** Pos Nr */
            pos_nr?: number | null;
            /**
             * Source Quote
             * @default
             */
            source_quote: string;
        };
        /**
         * Anfrage
         * @description Complete parsed RFQ.
         */
        Anfrage: {
            /** Belegnummer */
            belegnummer?: string | null;
            /** Datum */
            datum?: string | null;
            /** Kunde Firma */
            kunde_firma?: string | null;
            /** Kunde Ansprechpartner */
            kunde_ansprechpartner?: string | null;
            /** Kunde Email */
            kunde_email?: string | null;
            /** Kundennummer */
            kundennummer?: string | null;
            /** Incoterms */
            incoterms?: string | null;
            /** Zahlungsbedingungen */
            zahlungsbedingungen?: string | null;
            /** Positionen */
            positionen: components["schemas"]["Position"][];
            /** Unsicherheiten */
            unsicherheiten?: string[];
            /** Anforderungen */
            anforderungen?: components["schemas"]["Anforderung"][];
            /** Header Evidence */
            header_evidence?: {
                [key: string]: components["schemas"]["Evidence"];
            };
        };
        /** ApprovalTransitionRequest */
        ApprovalTransitionRequest: {
            /** Target */
            target: string;
            /** Actor */
            actor?: string | null;
            /** Warning Acknowledged */
            warning_acknowledged?: boolean | null;
            /** Exception Reason */
            exception_reason?: string | null;
            /** Changed Fields */
            changed_fields?: string[] | null;
        };
        /** Body_upload_mail_attachment_api_reviews__review_id__mail_attachments_post */
        Body_upload_mail_attachment_api_reviews__review_id__mail_attachments_post: {
            /** File */
            file: string;
        };
        /** Body_upload_review_api_reviews_upload_post */
        Body_upload_review_api_reviews_upload_post: {
            /** File */
            file: string;
        };
        /** CheckResult */
        CheckResult: {
            /** Name */
            name: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warning" | "error";
            /** Detail */
            detail: string;
        };
        /** CustomArticleRequest */
        CustomArticleRequest: {
            /** Pos Nr */
            pos_nr: number;
            /** Artikel Nr */
            artikel_nr: string;
            /** Bezeichnung */
            bezeichnung: string;
            /**
             * Einheit
             * @default Stk
             */
            einheit: string;
            /** Unit Price Eur */
            unit_price_eur: number;
            /** Werkstoff */
            werkstoff?: string | null;
            /** Abmessungen */
            abmessungen?: string | null;
        };
        /** DebugInfo */
        DebugInfo: {
            /**
             * Overall
             * @enum {string}
             */
            overall: "ok" | "warning" | "error";
            /** Checks */
            checks: components["schemas"]["CheckResult"][];
            /** Llm Provider */
            llm_provider: string;
            /** Checked At */
            checked_at: string;
            pipeline_failures: components["schemas"]["PipelineFailureSummary"];
            stammdaten_quality: components["schemas"]["StammdatenQuality"] | null;
        };
        /** EscalateRequest */
        EscalateRequest: {
            /** Reason */
            reason: string;
            /** Actor */
            actor?: string | null;
        };
        /**
         * Evidence
         * @description Source reference for a single extracted value.
         */
        Evidence: {
            /** Source File */
            source_file?: string | null;
            /** Source Page */
            source_page?: number | null;
            /** Source Row */
            source_row?: number | null;
            /** Source Quote */
            source_quote?: string | null;
        };
        /** FinalizeRequest */
        FinalizeRequest: {
            /** Actor */
            actor: string;
            /** Filename */
            filename?: string | null;
            /**
             * Warning Acknowledged
             * @default false
             */
            warning_acknowledged: boolean;
            /** Exception Reason */
            exception_reason?: string | null;
        };
        /** FinalizeResponse */
        FinalizeResponse: {
            /** Final Pdf Path */
            final_pdf_path: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LlmProbeResult */
        LlmProbeResult: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "error";
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Checked At */
            checked_at: string;
            /** Latency Ms */
            latency_ms: number;
            /** Detail */
            detail: string;
            /** Response Preview */
            response_preview?: string | null;
            /** Error Type */
            error_type?: string | null;
            usage?: components["schemas"]["LlmProbeUsage"] | null;
        };
        /** LlmProbeUsage */
        LlmProbeUsage: {
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /** MailAttachment */
        MailAttachment: {
            /** Name */
            name: string;
            /** Contenttype */
            contentType?: string | null;
            /** Size */
            size?: number | null;
            /** Id */
            id?: string | null;
            /** Contentbase64 */
            contentBase64?: string | null;
        };
        /**
         * MailAttachmentMeta
         * @description One attachment as stored alongside a review's mail payload.
         */
        MailAttachmentMeta: {
            /** Name */
            name: string;
            /** Contenttype */
            contentType?: string | null;
            /** Size */
            size?: number | null;
            /** Id */
            id?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * MailMeta
         * @description Mail header + body + attachments as the UI consumes them.
         */
        MailMeta: {
            /**
             * Subject
             * @default
             */
            subject: string;
            /**
             * From
             * @default
             */
            from: string;
            /**
             * Body
             * @default
             */
            body: string;
            /** Attachments */
            attachments?: components["schemas"]["MailAttachmentMeta"][];
        };
        /** MailReviewRequest */
        MailReviewRequest: {
            /** Subject */
            subject: string;
            /** From */
            from: string;
            /** Body */
            body: string;
            /**
             * Attachments
             * @default []
             */
            attachments: components["schemas"]["MailAttachment"][];
            /** Outlook Item Id */
            outlook_item_id?: string | null;
        };
        /** ManualMatchRequest */
        ManualMatchRequest: {
            /** Artikel Nr */
            artikel_nr: string;
        };
        /** MatchOverrideRequest */
        MatchOverrideRequest: {
            /** Pos Nr */
            pos_nr: number;
            /** Artikel Nr */
            artikel_nr: string;
        };
        /**
         * MatchResultModel
         * @description Mirror of ``quoting.matching.matcher.MatchResult.to_dict``.
         */
        MatchResultModel: {
            /** Pos Nr */
            pos_nr: number;
            /**
             * Status
             * @enum {string}
             */
            status: "exact" | "fuzzy" | "semantic" | "no_match";
            /** Score */
            score: number;
            /** Matched Artikelnr */
            matched_artikelnr?: string | null;
            /** Matched Bezeichnung */
            matched_bezeichnung?: string | null;
            /** Matched Row */
            matched_row?: {
                [key: string]: unknown;
            } | null;
            /**
             * Manual
             * @default false
             */
            manual: boolean;
        };
        /**
         * OutgoingMailAttachment
         * @description Additional file the user wants on the outgoing quotation email.
         */
        OutgoingMailAttachment: {
            /** Name */
            name: string;
            /** Contenttype */
            contentType?: string | null;
            /** Size */
            size?: number | null;
            /** Url */
            url: string;
        };
        /** PdfHighlightArea */
        PdfHighlightArea: {
            /** Pageindex */
            pageIndex: number;
            /** Left */
            left: number;
            /** Top */
            top: number;
            /** Width */
            width: number;
            /** Height */
            height: number;
        };
        /** PdfHighlightRequest */
        PdfHighlightRequest: {
            /** Source Page */
            source_page?: number | null;
            /** Source Quote */
            source_quote?: string | null;
            /** Candidates */
            candidates?: string[];
            /**
             * Target Kind
             * @default generic
             * @enum {string}
             */
            target_kind: "position" | "header" | "generic";
        };
        /** PdfHighlightResponse */
        PdfHighlightResponse: {
            /** Status */
            status: string;
            /** Areas */
            areas: components["schemas"]["PdfHighlightArea"][];
            /** Pageindex */
            pageIndex?: number | null;
            /** Matched Text */
            matched_text?: string | null;
            /** Message */
            message?: string | null;
        };
        /** PipelineFailure */
        PipelineFailure: {
            /** Review Id */
            review_id: string;
            /** Subject */
            subject: string;
            /** Sender */
            sender: string;
            /** Current Step */
            current_step: string;
            /** Error */
            error: string;
            /** Updated At */
            updated_at: string;
            /** Progress Percent */
            progress_percent: number;
        };
        /** PipelineFailureSummary */
        PipelineFailureSummary: {
            /** Total Failed */
            total_failed: number;
            /** Recent */
            recent: components["schemas"]["PipelineFailure"][];
        };
        /**
         * Position
         * @description One line item from an RFQ.
         */
        Position: {
            /** Pos Nr */
            pos_nr: number;
            /** Artikelnummer */
            artikelnummer: string;
            /**
             * Bezeichnung
             * @default
             */
            bezeichnung: string;
            /** Menge */
            menge: number;
            /** Einheit */
            einheit: string;
            /** Lieferzeit */
            lieferzeit?: string | null;
            /** Lieferwerk */
            lieferwerk?: string | null;
            /** Werkstoff */
            werkstoff?: string | null;
            /** Werkstoff Alternativen */
            werkstoff_alternativen?: string[];
            /** Zeichnungsnummer */
            zeichnungsnummer?: string | null;
            /** Abmessungen */
            abmessungen?: string | null;
            /** Gewicht Stueck Kg */
            gewicht_stueck_kg?: number | null;
            /** Gewicht Netto Kg */
            gewicht_netto_kg?: number | null;
            /** Gewicht Brutto Kg */
            gewicht_brutto_kg?: number | null;
            /** Verpackungsart */
            verpackungsart?: string | null;
            /**
             * Ist Zertifikat
             * @default false
             */
            ist_zertifikat: boolean;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Source Quote */
            source_quote: string;
            /** Source File */
            source_file?: string | null;
            /** Source Page */
            source_page?: number | null;
            /** Source Row */
            source_row?: number | null;
        };
        /**
         * QuotationItemModel
         * @description Mirror of ``quoting.pricing.quotation.QuotationItem``.
         */
        QuotationItemModel: {
            /** Pos Nr */
            pos_nr: number;
            /** Artikel Nr */
            artikel_nr: string;
            /** Bezeichnung */
            bezeichnung: string;
            /** Menge */
            menge: number;
            /** Einheit */
            einheit: string;
            /** Einzelpreis */
            einzelpreis: number;
            /**
             * Rabatt Prozent
             * @default 0
             */
            rabatt_prozent: number;
            /** Gesamtpreis */
            gesamtpreis: number;
            /**
             * Bemerkung
             * @default
             */
            bemerkung: string;
            /**
             * Basispreis Eur
             * @default 0
             */
            basispreis_eur: number;
            /**
             * Margin Eur
             * @default 0
             */
            margin_eur: number;
            /**
             * Margin Pct
             * @default 0
             */
            margin_pct: number;
        };
        /**
         * QuotationModel
         * @description Mirror of ``quoting.pricing.quotation.Quotation.to_dict``.
         */
        QuotationModel: {
            /** Kunde Firma */
            kunde_firma?: string | null;
            /** Kunde Ansprechpartner */
            kunde_ansprechpartner?: string | null;
            /** Kunde Email */
            kunde_email?: string | null;
            /** Kundennummer */
            kundennummer?: string | null;
            /** Belegnummer */
            belegnummer?: string | null;
            /** Incoterms */
            incoterms?: string | null;
            /** Zahlungsbedingungen */
            zahlungsbedingungen?: string | null;
            /** Items */
            items: components["schemas"]["QuotationItemModel"][];
            /** Gesamtsumme */
            gesamtsumme: number;
            /** Waehrung */
            waehrung: string;
            /** Warnungen */
            warnungen: string[];
        };
        /**
         * ReplyBodyResponse
         * @description LLM-generated cover-letter body for the Outlook reply.
         */
        ReplyBodyResponse: {
            /** Body */
            body: string;
            /**
             * Language
             * @enum {string}
             */
            language: "de" | "en";
            /** Model */
            model: string;
        };
        /** RequirementsAckRequest */
        RequirementsAckRequest: {
            /** Indices */
            indices?: number[];
        };
        /**
         * ReviewDetail
         * @description Full payload returned by ``GET /api/reviews/{id}``.
         */
        ReviewDetail: {
            /** Review Id */
            review_id: string;
            /** Created At */
            created_at?: string | null;
            anfrage: components["schemas"]["Anfrage"];
            original_anfrage: components["schemas"]["Anfrage"];
            /** Matches */
            matches?: components["schemas"]["MatchResultModel"][];
            quotation?: components["schemas"]["QuotationModel"] | null;
            /** Manual Overrides */
            manual_overrides?: {
                [key: string]: unknown;
            }[];
            mail: components["schemas"]["MailMeta"];
            /** Has Draft Pdf */
            has_draft_pdf: boolean;
            /** Has Final Pdf */
            has_final_pdf: boolean;
            /** Mail Attachments */
            mail_attachments?: components["schemas"]["OutgoingMailAttachment"][];
            /** Requirements Acknowledged */
            requirements_acknowledged?: number[];
            /** Escalation */
            escalation?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ReviewListItem
         * @description One row in ``GET /api/reviews``.
         */
        ReviewListItem: {
            /** Review Id */
            review_id: string;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Subject */
            subject: string;
            /** Sender */
            sender: string;
            /**
             * Customer
             * @default
             */
            customer: string;
            /** Positions */
            positions: number;
            /** Confidence High */
            confidence_high: number;
            /** Confidence Medium */
            confidence_medium: number;
            /** Confidence Low */
            confidence_low: number;
            /** Matches Exact */
            matches_exact: number;
            /** Matches Fuzzy */
            matches_fuzzy: number;
            /** Matches Semantic */
            matches_semantic: number;
            /** Matches No Match */
            matches_no_match: number;
            /** Total Eur */
            total_eur: number;
            /** Currency */
            currency: string;
            /**
             * Status
             * @enum {string}
             */
            status: "abgeschlossen" | "pdf_bereit" | "in_arbeit";
            /** Has Pdf */
            has_pdf: boolean;
            /** Manual Overrides Count */
            manual_overrides_count: number;
            /** Escalation */
            escalation?: {
                [key: string]: unknown;
            } | null;
            /** Extracted Articles */
            extracted_articles?: string[];
        };
        /** StammdatenHit */
        StammdatenHit: {
            /** Artikel Nr */
            artikel_nr: string;
            /** Bezeichnung */
            bezeichnung: string;
            /** Werkstoff */
            werkstoff?: string | null;
            /** Abmessungen */
            abmessungen?: string | null;
            /**
             * Einheit
             * @default ST
             */
            einheit: string;
            /**
             * Basispreis Eur
             * @default 0
             */
            basispreis_eur: number;
            /**
             * Preis Min Eur
             * @default 0
             */
            preis_min_eur: number;
            /**
             * Preis Max Eur
             * @default 0
             */
            preis_max_eur: number;
            /**
             * N Offers
             * @default 0
             */
            n_offers: number;
            /** Sales Group */
            sales_group?: string | null;
            /** Material Group */
            material_group?: string | null;
            /**
             * Score
             * @default 1
             */
            score: number;
        };
        /** StammdatenQuality */
        StammdatenQuality: {
            /** Path */
            path: string;
            /** Total Rows */
            total_rows: number;
            /** File Size Kb */
            file_size_kb: number;
            /** Last Modified */
            last_modified: string;
            /** Duplicate Article Numbers */
            duplicate_article_numbers: number;
            /** Missing Article Numbers */
            missing_article_numbers: number;
            /** Missing Descriptions */
            missing_descriptions: number;
            /** Zero Or Missing Prices */
            zero_or_missing_prices: number;
            /** Invalid Price Ranges */
            invalid_price_ranges: number;
            /** Single Offer Articles */
            single_offer_articles: number;
            /** Missing Materials */
            missing_materials: number;
            /** Missing Dimensions */
            missing_dimensions: number;
            /** Sample Duplicate Articles */
            sample_duplicate_articles: string[];
            /** Sample Zero Price Articles */
            sample_zero_price_articles: string[];
        };
        /** TablePreview */
        TablePreview: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Total Rows */
            total_rows: number;
            /** Truncated */
            truncated: boolean;
            /** Sheet Names */
            sheet_names?: string[];
            /** Active Sheet */
            active_sheet?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_metrics_api_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_reviews_api_reviews_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewListItem"][];
                };
            };
        };
    };
    create_review_api_reviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MailReviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_by_outlook_item_query_api_reviews_by_outlook_item_get: {
        parameters: {
            query: {
                outlook_item_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_by_outlook_item_api_reviews_by_outlook_item__outlook_item_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outlook_item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_outlook_item_query_api_reviews_by_outlook_item_detach_post: {
        parameters: {
            query: {
                outlook_item_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detach_outlook_item_api_reviews_by_outlook_item__outlook_item_id__detach_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                outlook_item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_review_opened_api_reviews__review_id__mark_opened_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_detail_api_reviews__review_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_review_api_reviews__review_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_mail_api_reviews__review_id__mail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailMeta"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_anfrage_api_reviews__review_id__anfrage_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Anfrage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_overrides_api_reviews__review_id__overrides_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_requirements_ack_api_reviews__review_id__requirements_ack_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementsAckRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_quotation_api_reviews__review_id__regenerate_post: {
        parameters: {
            query?: {
                build_pdf?: boolean;
            };
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuotationModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_reply_body_api_reviews__review_id__reply_body_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyBodyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_quotation_api_reviews__review_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    escalate_review_api_reviews__review_id__escalate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_escalation_api_reviews__review_id__escalate_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_pipeline_api_reviews__review_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_review_events_api_reviews__review_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_attachment_api_reviews__review_id__attachment__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_mail_attachments_api_reviews__review_id__mail_attachments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_mail_attachment_api_reviews__review_id__mail_attachments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_mail_attachment_api_reviews__review_id__mail_attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mail_attachment_api_reviews__review_id__mail_attachments__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_mail_attachment_api_reviews__review_id__mail_attachments__filename__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pdf_source_highlight_api_reviews__review_id__attachment__filename__pdf_highlight_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
                filename: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PdfHighlightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PdfHighlightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_original_api_reviews__review_id__original_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_original_table_api_reviews__review_id__original_preview_get: {
        parameters: {
            query?: {
                /** @description XLSX sheet name, default: first */
                sheet?: string | null;
            };
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TablePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_review_api_reviews_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_review_api_reviews_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_stammdaten_api_stammdaten_search_get: {
        parameters: {
            query?: {
                /** @description Free-text query */
                q?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StammdatenHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    override_match_api_reviews__review_id__match_override_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatchOverrideRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_manual_match_api_reviews__review_id__matches__pos_nr__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
                pos_nr: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualMatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_custom_article_match_api_reviews__review_id__custom_article_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomArticleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_debug_info_api_debug_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugInfo"];
                };
            };
        };
    };
    probe_llm_provider_api_debug_llm_post: {
        parameters: {
            query?: {
                timeout_s?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LlmProbeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_status_api_reviews__review_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_api_reviews__review_id__approval_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_approval_api_reviews__review_id__approval_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalTransitionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_review_api_reviews__review_id__reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_pdf_api_reviews__review_id__pdf_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_draft_pdf_api_reviews__review_id__pdf_draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_final_pdf_api_reviews__review_id__pdf_final_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                review_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
